name: Android APK (Buildozer)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y build-essential git unzip zip \
            openjdk-11-jdk python3-pip python3-setuptools python3-wheel \
            libffi-dev libssl-dev libjpeg-dev zlib1g-dev libbz2-dev \
            libncurses5-dev libreadline-dev libsqlite3-dev

      # نصب commandline-tools و افزودن به PATH
      - name: Install Android commandline tools
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          unzip -q cmdtools.zip
          mv cmdline-tools latest
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

      # نصب SDK/NDK و Build-Tools لازم و ست‌کردن متغیرها برای Buildozer
      - name: Install Android SDK packages
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          yes | sdkmanager --licenses
          sdkmanager --update
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"
          echo "$ANDROID_SDK_ROOT/build-tools/33.0.2" >> $GITHUB_PATH
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROIDSDK=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROIDNDK=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROIDAPI=33" >> $GITHUB_ENV
          echo "ANDROIDMINAPI=21" >> $GITHUB_ENV

      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          pip install cython kivy buildozer

      - name: Build APK (debug)
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
