name: Android APK (Buildozer)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y build-essential git unzip zip \
            openjdk-11-jdk python3-pip python3-setuptools python3-wheel \
            libffi-dev libssl-dev libjpeg-dev zlib1g-dev libbz2-dev libncurses5-dev libreadline-dev libsqlite3-dev

      - name: Install Android commandline tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-10406996_latest.zip
          mv cmdline-tools latest
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/build-tools/33.0.2:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK Build Tools
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --update
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          pip install kivy buildozer cython

      - name: Build APK (debug)
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
